FROM node:0.12
MAINTAINER Manuel Garcia <manuel.garcia@altoros.com> / <mgarciap@gmail.com>

# Installl Node-Red version 0.11.2
RUN npm install -g node-red@0.11.2

EXPOSE 1880
CMD ["/usr/local/bin/node-red"]
